Update readme files
PilzDE/pilz_testutils pull request #11
Opened 2019-11-28 14:49 UTC by HiddenBug

2019-11-29 09:17 UTC, martiniil submitted a review, later dismissed
Please commit my suggestion and merge.

2019-11-29 09:17 UTC, martiniil commented on pilz_robot_tfc_api/README.md
> +This packages contains the API's for Python and C++,
```suggestion
This packages contains the API's for Python and C++
```

2019-12-02 08:44 UTC, jschleicher commented
Is the name clash of the repo with [pilz_testutils inside pilz_robots](https://github.com/PilzDE/pilz_robots/tree/melodic-devel/pilz_testutils) intended? Should this package(s) replace the former one?

2019-12-02 09:08 UTC, martiniil commented
> Is the name clash of the repo with [pilz_testutils inside pilz_robots](https://github.com/PilzDE/pilz_robots/tree/melodic-devel/pilz_testutils) intended? Should this package(s) replace the former one?

Actually, it was not intended. But yes, the package `pilz_testutils` in `pilz_robots` can be dissolved in the future.

2019-12-02 09:20 UTC, martiniil requested changes

2019-12-02 09:20 UTC, martiniil commented on README.md
> +[pilz_robot_tfc_api](pilz_robot_tfc_api/README.md) contains the API to
```suggestion
[pilz_robot_tfc_api](pilz_robot_tfc_api/README.md) contains the Python and C++ API's for
```

2019-12-02 09:20 UTC, martiniil commented on README.md
> +programmatically control the robot test facility via test.
```suggestion
programmatically controlling the PILZ robot test facility via test.
```

2019-12-02 09:20 UTC, martiniil commented on pilz_robot_tfc_api/README.md
> +This packages contains the API's for Python and C++
```suggestion
This packages contains the Python and C++ API's for
```

2019-12-02 09:20 UTC, martiniil commented on pilz_robot_tfc_api/README.md
> +to programmatically control the PILZ robot test facility via test.
```suggestion
programmatically controlling the PILZ robot test facility via test.
```

2019-12-02 09:36 UTC, martiniil approved these changes

2019-12-02 09:38 UTC, merged